#!/bin/sh
release="kano_$1-$2"

mkdir "build/$release"
mkdir "build/$release/usr"
mkdir "build/$release/usr/local"
mkdir "build/$release/usr/local/bin"

go build -o "build/$release/usr/local/bin/kano" -ldflags "-s -w" github.com/drabiter/kano

mkdir "build/$release/DEBIAN"
echo "Package: kano" >  "build/$release/DEBIAN/control"
echo "Version: $1-$2" >>  "build/$release/DEBIAN/control"
echo "Section: base" >>  "build/$release/DEBIAN/control"
echo "Priority: optional" >>  "build/$release/DEBIAN/control"
echo "Architecture: i386" >>  "build/$release/DEBIAN/control"
echo "Maintainer: drabiter" >>  "build/$release/DEBIAN/control"
echo "Description: kano" >>  "build/$release/DEBIAN/control"

dpkg-deb --build "build/$release"

mv "build/$release/usr/local/bin/kano" "build/"

rm -r "build/$release"
